defmodule ExchemaExtra.Types.CNPJTest do
  use ExUnit.Case
  use ExUnitProperties

  alias ExchemaExtra.Types, as: T

  property "all generated cnpjs with stream data types are valid" do
    check all cnpj <- ExchemaStreamData.gen(T.CNPJ, &ExchemaExtra.StreamData.override/2) do
      assert Exchema.is?(cnpj, Exchema.Types.String)
      assert Brcpfcnpj.cnpj_valid?(%Cnpj{number: cnpj})
      assert Exchema.is?(cnpj, T.CNPJ)
    end
  end

  property "all cnpjs generated by groundtruth are valid" do
    check all groundtruth <- map(nil, fn _ -> Brcpfcnpj.cnpj_generate() end) do
      assert Exchema.is?(groundtruth, T.CNPJ)
    end
  end
end
