defmodule ExchemaExtra.Types.CPFTest do
  use ExUnit.Case
  use ExUnitProperties

  alias ExchemaExtra.Types, as: T

  property "all generated cpfs with stream data types are valid" do
    check all cpf <- ExchemaStreamData.gen(T.CPF, &ExchemaExtra.StreamData.override/2) do
      assert Exchema.is?(cpf, Exchema.Types.String)
      assert Brcpfcnpj.cpf_valid?(%Cpf{number: cpf})
      assert Exchema.is?(cpf, T.CPF)
    end
  end

  property "all cpfs generated by groundtruth are valid" do
    check all groundtruth <- map(nil, fn _ -> Brcpfcnpj.cpf_generate() end) do
      assert Exchema.is?(groundtruth, T.CPF)
    end
  end
end
